notifications:
  email: false

sudo: required
language: python
services:
  - docker
env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64

install:
  - docker pull $DOCKER_IMAGE
  - pip install twine

before_script:
  - sudo chmod +x ./CI/build-wheels.sh

script:
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE io/CI/build-wheels.sh
  - python -m twine check dist/* wheelhouse/*
  - python -m twine upload wheelhouse/*.whl -u $TWINE_USERNAME -p $TWINE_PASSWORD
